import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./css/global.scss";
import Container from "./components/Container";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Forumify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Container>{children}</Container>
      </body>
    </html>
  );
}
